"""AES-256 encrypted PDF prescription generator — AZOTH_OS_SYNC=FALSE fallback.

Generates a password-protected PDF for SMTP dispatch to compounding pharmacies.
"""
import io
import os
import hashlib
from datetime import datetime, timezone
from typing import Optional

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

from app.services.magistral_calculator import DosageCalculation


def generate_prescription_pdf(
    calculation: DosageCalculation,
    provider_name: str,
    patient_alias: str,
    prescription_id: str,
    provider_npi: Optional[str] = None,
    clinic_name: str = "MPMP Practice",
    clinic_address: str = "",
) -> tuple[bytes, str]:
    """Generate a prescription PDF and return (pdf_bytes, sha256_hash).

    The PDF is NOT password-encrypted here — that's handled by the
    SMTP dispatcher using the pharmacy's shared key. This function
    produces the plaintext PDF for signing and archival.
    """
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    width, height = letter

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(1 * inch, height - 1 * inch, clinic_name)
    c.setFont("Helvetica", 9)
    if clinic_address:
        c.drawString(1 * inch, height - 1.3 * inch, clinic_address)

    # Prescription details
    y = height - 2 * inch
    c.setFont("Helvetica-Bold", 12)
    c.drawString(1 * inch, y, "PRESCRIPTION ORDER")
    c.line(1 * inch, y - 5, width - 1 * inch, y - 5)

    y -= 30
    c.setFont("Helvetica", 10)
    fields = [
        ("Rx ID:", prescription_id),
        ("Date:", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")),
        ("Patient Alias:", patient_alias),
        ("Provider:", provider_name),
    ]
    if provider_npi:
        fields.append(("NPI:", provider_npi))

    for label, value in fields:
        c.setFont("Helvetica-Bold", 10)
        c.drawString(1 * inch, y, label)
        c.setFont("Helvetica", 10)
        c.drawString(2.5 * inch, y, value)
        y -= 18

    # Medication details
    y -= 15
    c.setFont("Helvetica-Bold", 12)
    c.drawString(1 * inch, y, "MEDICATION")
    c.line(1 * inch, y - 5, width - 1 * inch, y - 5)
    y -= 25

    med_fields = [
        ("Compound:", calculation.compound),
        ("Vial Size:", f"{calculation.vial_size_mg} mg"),
        ("Diluent:", f"{calculation.diluent_ml} mL Bacteriostatic Water"),
        ("Target Dose:", f"{calculation.target_dose_mcg} mcg"),
        ("Draw Volume:", f"{calculation.draw_volume_ml} mL ({calculation.syringe_units:.0f} Units)"),
        ("Syringe:", calculation.syringe_type),
        ("Doses/Vial:", str(calculation.doses_per_vial)),
    ]

    for label, value in med_fields:
        c.setFont("Helvetica-Bold", 10)
        c.drawString(1 * inch, y, label)
        c.setFont("Helvetica", 10)
        c.drawString(2.5 * inch, y, value)
        y -= 18

    # Instructions
    y -= 15
    c.setFont("Helvetica-Bold", 12)
    c.drawString(1 * inch, y, "PATIENT INSTRUCTIONS")
    c.line(1 * inch, y - 5, width - 1 * inch, y - 5)
    y -= 25
    c.setFont("Helvetica", 10)

    # Word wrap the instruction text
    words = calculation.human_readable.split()
    line = ""
    for word in words:
        test = line + " " + word if line else word
        if c.stringWidth(test, "Helvetica", 10) > (width - 2 * inch):
            c.drawString(1 * inch, y, line)
            y -= 15
            line = word
        else:
            line = test
    if line:
        c.drawString(1 * inch, y, line)

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(1 * inch, 0.75 * inch, "CONFIDENTIAL — For authorized pharmacy use only")
    c.drawString(1 * inch, 0.5 * inch, f"Generated by {clinic_name} via MPMP")

    c.save()
    pdf_bytes = buf.getvalue()
    pdf_hash = hashlib.sha256(pdf_bytes).hexdigest()

    return pdf_bytes, pdf_hash
